### ISSUE TITLE
Tutorial crashed when start play

### ISSUE THREAD

**Issue by james-yoo** [rticommunity/rticonnextdds-usecases-unreal#1]
First of all, thank you very much for providing this detailed tutorial. I was thinking about how to link the Unreal Engine with DDS, and this tutorial will be a great reference. However, there was a problem following the tutorial.

My development environment is as follows :

- Windows 10 x64
- Visual Studio 2019 Community
- RTI connext Pro evaluation (6.0.1)
- Unreal Engine 4.26.1 / 4.25.4

When running play on tutorial [module 6](https://www.rti.com/developers/case-code/unrealengine-sim-m6), unreal engine has crashed with following message:
![image](https://user-images.githubusercontent.com/23667624/114258814-371b1300-9a04-11eb-9568-acbc06f1a31a.png)

An error occurred in Line 55 of ShapeSub.cpp file, which is as follows:
dds::domain::DomainParticipant participant = dds::domain::DomainParticipant(DomainID);

The Connext settings of blueprint class are set to Square and domain zero as default. 
![image](https://user-images.githubusercontent.com/23667624/114259020-e7d5e200-9a05-11eb-902d-0a147abd6a09.png)

Do you have any ideas regarding of this issue?

Thanks.

**Comment by james-yoo** [comment]
**Update:**
I found that when the blueprint class 'SquareSub' place to the level, the crash occurs.

**Comment by andre-rti** [comment]
James, 

Since you are using the evaluation version my guess is that the license file can't be found since it fails in the domain participant creation. Do you have the environment variable NDDSHOME set and a valid license file in %NDDSHOME%?

You can also set the license file location in the QoS XML file (see [the License Management Section](https://community.rti.com/static/documentation/connext-dds/6.0.1/doc/manuals/connext_dds/html_files/RTI_ConnextDDS_InstallationGuide/index.htm#InstallationGuide/License_Management.htm%3FTocPath%3D_____5) in the installation guide. 

Andre

**Comment by james-yoo** [comment]
Issue resolved by setting correct licence file path (e.g. NDDSHOME variable). 

Thanks,
James
